### ISSUE TITLE
_valueToSum with a wrong accuracy

### ISSUE THREAD

**Issue by songhailiang** [facebook/facebook-objc-sdk#1012]
Hello all,
I'm using FBSDKCoreKit framework of version 5.2.3 in my Swift App.
I'm trying to log addToCart event, here is my code,
```
var params: [String: Any] = [:]
params[AppEvents.ParameterName.contentID.rawValue] = xxx
params[AppEvents.ParameterName.currency.rawValue] = xxx
AppEvents.logEvent(.addedToCart, valueToSum: price, parameters: params)
```
The ```price``` is ```Double```  type with value of 9.99.
But i will get a wrong accuracy value of ```_valueToSum``` from Charles.
e.g:
"custom_events": "[{\"_eventName\":\"fb_mobile_add_to_cart\",\"fb_currency\":\"EUR\",\"_logTime\":1565683598,\"_valueToSum\":9.9900000000000002,\"_ui\":\"xxxx\"}]"

"custom_events": "[{\"_eventName\":\"fb_mobile_add_to_cart\",\"fb_currency\":\"EUR\",\"_logTime\":1565683270,\"_valueToSum\":99.989999999999995,\"_ui\":\"xxxx\"}]",

I'm not sure if this is a bug or not.
My concern is if this will affect the summarized statistics in the dashboard of Facebook. 
Is there a workaround to fix this?

Thanks,
Hailiang

**Comment by joesus** [comment]
@songhailiang thank you for asking. I would respectfully ask that you redirect your question to our developer support team <https://developers.facebook.com/support/bugs>. They will be able to provide a faster resolution. Closing the issue. Thank you!
