### ISSUE TITLE
sourceApplication is nil when logging in through FB app

### ISSUE THREAD

**Issue by marianoprettysimple** [facebook/facebook-objc-sdk#1014]
On **iOS 13 beta 7**, building my app with **Xcode11.0 beta 5 / FB SDK 5.3.0**, if the FB login is done through the FB app, when the FB app launches my app, my app's `UIApplicationDelegate` receives an `application:openURL:sourceApplication:annotation:` call. In this call, the sourceApplication should be `"com.facebook.Facebook"` but is `nil`. 

Then, when the parameters are passed to `[FBSDKApplicationDelegate application:openURL:sourceApplication:annotation:]` it returns `NO`.

If, before logging in through my app, I sign into FB in Safari, then the login doesn't involve the FB app and it works as expected.

Using the same build on a different device running iOS 12, the issue is not there.

**Comment by joesus** [comment]
@marianoprettysimple, thank you for asking. This is a totally valid question but I would respectfully ask that you redirect it to our developer support team https://developers.facebook.com/support/bugs. They will be able to provide a faster resolution. Closing the issue. Thank you!

**Comment by dreamolight** [comment]
Apple removed the access to sourceApplication in iOS 13 beta: https://developer.apple.com/videos/play/wwdc2019/708/.

And we've removed the check for "com.facebook" in SDK to support iOS 13 beta.
