### ISSUE TITLE
where do I find the frameworks for manual install?

### ISSUE THREAD

**Issue by pangia** [facebook/facebook-objc-sdk#1018]
where do I find the frameworks for manual install?

**Comment by joesus** [comment]
You can find the frameworks under the 'releases' tab of the 'code' tab. 
![image](https://user-images.githubusercontent.com/4922820/63365504-9ce8f180-c32c-11e9-8a33-2b8c2d70cc43.png)

**Comment by pangia** [comment]
Will that release include the latest fixes for iOS13 login issues?

**Comment by joesus** [comment]
If I understand correctly, yes. The upcoming release will have fixes and
will also be available for download at that location.
