### ISSUE TITLE
build failed with Xcode 11 beta 6

### ISSUE THREAD

**Issue by fromkk** [facebook/facebook-objc-sdk#1021]
error log is here.

```
/Users/username/MyApp/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/Internal/FBSDKVideoUploader.m:26:9: fatal error: 'FBSDKCoreKit+Internal.h' file not found
#import "FBSDKCoreKit+Internal.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

## Environment

- OS: macOS Mojave 10.14.6 (18G87)
- Xcode: Version 11.0 beta 6 (11M392q)
- CocoaPods: 1.7.5
- SDK Version: 5.4.1

## Podfile

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
project 'MyApp.xcodeproj'
inhibit_all_warnings!

install! 'cocoapods',
  generate_multiple_pod_projects: true,
  incremental_installation: true

target 'MyApp' do
  use_frameworks!

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
      end
    end
  end
end
```

**Comment by dreamolight** [comment]
HI @rakesthedon , could you also share the log for `pod install`?

**Comment by rakesthedon** [comment]
I remove my comment since I wasn't using cocoapods

**Comment by reuvenlevitsky** [comment]
Hey @dreamolight 

It looks like Facebook Frameworks doesn't play nice with new Cocoapods flag `generate_multiple_pod_projects: true`

Here is the issue reported in the Cocoapods repo: https://github.com/CocoaPods/CocoaPods/issues/8853

**Comment by dreamolight** [comment]
Hi @reuvenlevitsky , thanks for pointing out the solution, we'll fix it in next release which I expect within 2 weeks.

**Comment by dreamolight** [comment]
Closing this as 5.6.0 released with the support for generate_multiple_pod_projects.

**Comment by wangjunhua1** [comment]
> error log is here.
> 
> ```
> /Users/username/MyApp/Pods/FBSDKShareKit/FBSDKShareKit/FBSDKShareKit/Internal/FBSDKVideoUploader.m:26:9: fatal error: 'FBSDKCoreKit+Internal.h' file not found
> #import "FBSDKCoreKit+Internal.h"
>         ^~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> ## Environment
> * OS: macOS Mojave 10.14.6 (18G87)
> * Xcode: Version 11.0 beta 6 (11M392q)
> * CocoaPods: 1.7.5
> * SDK Version: 5.4.1
> 
> ## Podfile
> ```
> source 'https://github.com/CocoaPods/Specs.git'
> platform :ios, '9.0'
> project 'MyApp.xcodeproj'
> inhibit_all_warnings!
> 
> install! 'cocoapods',
>   generate_multiple_pod_projects: true,
>   incremental_installation: true
> 
> target 'MyApp' do
>   use_frameworks!
> 
>   pod 'FBSDKCoreKit'
>   pod 'FBSDKLoginKit'
>   pod 'FBSDKShareKit'
> end
> 
> post_install do |installer|
>   installer.generated_projects.each do |project|
>     project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings.delete('CODE_SIGNING_ALLOWED')
>         config.build_settings.delete('CODE_SIGNING_REQUIRED')
>       end
>     end
>   end
> end
> ```



you can add  this 

# fix FBSDKCoreKit  generate_multiple_pod_projects link false  https://github.com/CocoaPods/CocoaPods/issues/8856
def append_header_search_path(target, path)
    target.build_configurations.each do |config|
        # Note that there's a space character after `$(inherited)`.
        config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
        config.build_settings["HEADER_SEARCH_PATHS"] << path
    end
end

  post_install do |installer|
    installer.pod_target_subprojects.flat_map { |p| p.targets }.each do |t|
      # `RxDataSources` is a pod lib which depends the `RxCocoa` lib.
      if t.name == "FBSDKLoginKit"
        append_header_search_path(t, "${PODS_ROOT}/Headers/Public/FBSDKCoreKit")
      end
    end
  end
