### ISSUE TITLE
FBSDKMarketingKit podspec out of date

### ISSUE THREAD

**Issue by giilby** [facebook/facebook-objc-sdk#1024]
It looks like the podspec for `FBSDKMarketingKit` is out of date: https://github.com/CocoaPods/Specs/commit/2bdf2e2b62198a4ac3c6831c8446c569b9b1470d

I noticed this after attempting to upgrade to the latest version of `FacebookSDK` (v5.4.1). After running `pod update`, CocoaPods informed me that `FBSDKCoreKit` was still out of date. I believe this is because the latest published spec for `FBSDKMarketingKit` pins to an exact version of `FBSDKCoreKit` (v5.0.0).

**Comment by dreamolight** [comment]
Hi @giilby , thanks for bring this up, we'll release a new version of `FBSDKMarketingKit` (v5.5.0) to fix this issue after holiday. And the dependency to `FBSDKCoreKit` will be updated to `~> 5.5` instead of exact version.

**Comment by giilby** [comment]
@dreamolight Sounds good. Thanks!

**Comment by dreamolight** [comment]
Closing this as `FBSDMMarketingKit` updated to `5.5.0`.
