### ISSUE TITLE
New Event Names Do Not Appear in Ads Manager

### ISSUE THREAD

**Issue by ryanbeckpray** [facebook/facebook-objc-sdk#1026]
We noticed a change in the events that are sent to FB when a customer starts a free trial. In v5.0.2 we noticed a Purchase event was sent. When we upgraded to v5.2.2 (the newest release at the time), we noticed that a Start Trial replaced the purchase event. Ever since this change we are no longer able to see the Start Trial event in our Ads Manager/Ads Reporting dashboards; it is, however, visible in FB analytics and Events Manager.

We previously saw the Purchase event in the Ads Reporting, Event Manager, and FB Analytics. That is not the case for the new Start Trial.

I expect that when we upgraded the SDK, if an event name changed, it would work without additional configuration changes in the App integration or FB Business Tools Dashboards.

We also noticed other events were changed as well, such as Initiate Purchase was changed to SubscriptionInitiatePurchase.

I have confirmed that this indeed is the problem. We took the same code and simply changed the FB SDK and everything works as expected in v5.0.2 of the FB SDK and things do not work as expected in v5.2.2, namely "Initiate Purchase" is changed to "SubscriptionInitiatePurchase" and "Purchase" has gone away completely. 

Furthermore, Ads Manager doesn't recognize "SubscriptionInitiatePurchase" as a standard event and doesn't properly attribute "Start Trial" events to the ads, but it does attribute "Purchase" to the ads. So this does not appear to be an attribution issue.

This is a real problem when we try to optimize the Ads.

I believe this problem was introduced in v5.1.0 when logImplicitPurchaseEvent was replaced to utilize logImplicitSubscriptionTransaction, logImplicitSubscribeEvent, and logImplicitPurchaseTransaction. These methods utilize new event names introduced by v5.0.0 in the  FBSDKPaymentObserver.m

Here is the original commit that introduced the name changes
https://github.com/facebook/facebook-objc-sdk/commit/711540d840b0f3b744d4e70faaeb483c199cdbf6

Here is the commit that I think activated those new events in v5.0.0 (I could be wrong here and would love clarification on the issue.)
https://github.com/facebook/facebook-objc-sdk/commit/bed268b0b87b7481d63b55f89b926448e91540fb

Here is the Changes between those versions.
https://github.com/facebook/facebook-objc-sdk/compare/v5.0.2...v5.1.0

**Comment by YOUDAN** [comment]
What's your app id?

**Comment by dreamolight** [comment]
Hi @ryanbeckpray , SDK is working as expected, the issue should be at ads manager side, please file a bug report here: https://developers.facebook.com/support/bugs/, we'll have engineers from ads manager team to do further investigation.
