### ISSUE TITLE
Replace UIWebViews in FBSDKCoreKit

### ISSUE THREAD

**Issue by achager** [facebook/facebook-objc-sdk#1028]
Today when submitting a new version of an application I am working on that utilizes FBSDKLoginKit and FBSDKCoreKit I received an email from Apple stating my application had one or more issues, with the reasoning being around UIWebView API usage. The application does not contain any web views, and when I searched I found references to UIWebView in `FBSDKWebDialogView` and `FBSDKWebViewAppLinkResolver`. These should be updated to use WKWebView.

The message from Apple: 

`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.`

**Comment by dreamolight** [comment]
Hi there, we'll have a release soon this week, with this coming release, we replaced most of the UIWebViews with WKWebView, however, on iOS 8, WKWebView doesn't the equivalent API UIWebView provides: `loadData:MIMEType:textEncodingName:baseURL:`. So if the minimum OS version required for your app is >= 9.0, UIWebView won't be used.

Please let us know if you can still see the issue when submitting with next version of FB SDK.

**Comment by dreamolight** [comment]
5.5.0 has been released with all UIWebView replaced.

**Comment by nikletsopen** [comment]
@dreamolight  Hi! I've updated my pods to the latest version, but references to UIWebView are still there.

**Comment by ramizIdealz** [comment]
same here , they are still there in the FBSDKWebdialogView

**Comment by nikletsopen** [comment]
@ramizIdealz try to do pod update with `pod 'FacebookSDK/CoreKit'` instead of just  `pod 'FacebookSDK'` it has helped me to update to the version 5.5.0 with UIWebView replacement

**Comment by awthonest** [comment]
CocoaPods could not find compatible versions for pod "FacebookSDK":
  In Podfile:
    FacebookSDK (~> 5.5.0)

None of your spec sources contain a spec satisfying the dependency: `FacebookSDK (~> 5.5.0)`.

**Comment by awthonest** [comment]
CocoaPods could not find compatible versions for pod "FacebookSDK/CoreKit":
  In Podfile:
    FacebookSDK/CoreKit (~> 5.5.0)

None of your spec sources contain a spec satisfying the dependency: `FacebookSDK/CoreKit (~> 5.5.0)`.

**Comment by ramizIdealz** [comment]
Agree with @awthonest , i also got the same error, couldn't find pod that has UIWebview replaced

**Comment by dreamolight** [comment]
Since 5.5.0 was released not long ago, you need to `pod update` first or use `pod install --repo-update` instead of `pod install`.

**Comment by ramizIdealz** [comment]
solved, thanks a lot , @dreamolight

**Comment by serdnah2** [comment]
@dreamolight You are rock! Thanks

**Comment by premkumarsepuri** [comment]
pod 'FBSDKCoreKit'
        pod 'FBSDKLoginKit'
        pod 'FBSDKShareKit'

I got rejected mail from apple fro using above pods which have Uiwebview . can any one give updated pods . project is in objective c
