### ISSUE TITLE
App links: FBSDKURL defined as NS_ASSUME_NONNULL_BEGIN but appLinkData can be nil

### ISSUE THREAD

**Issue by pcabfever** [facebook/facebook-objc-sdk#1030]
Hello

The whole file FBSDKURL.h is defined as NS_ASSUME_NONNULL_BEGIN but the documentation for the appLinkData states that it can be nil.

Checking the implementation it seems like it could be nil

How are we supposed to check if an URL is an app link from Swift then?

```
let parsedURL = AppLinkURL(inboundURL: url, sourceApplication: sourceApplication)
parsedURL.appLinkData != nil //this throws a warning as the compile assumes it as non optional
```

Thanks a lot

**Comment by tianqibt** [comment]
We have added nullable to the property. You can use the `parsedURL.appLinkData != nil` to check if an URL is an app link without the warning. The change will go into our next release.
