### ISSUE TITLE
Login always returns cancel v5.5.0, ios 13 Xcode 11 beta 6

### ISSUE THREAD

**Issue by odedharth** [facebook/facebook-objc-sdk#1032]
Xcode Version: 11.0 Beta 6
iOS Version: 13.1
Swift Version: 4.2
SDK Version: 5.5.0

**Goals**
Login With Facebook

**Expected Results**
Perform login without canceling in Safari

**Actual Results**
Login always returns with result.isCancelled set to true.
No Safari WebViewController is presented...

**Steps to Reproduce:**
Pretty simple - just create a login manager and try to login. The exact code is working fine in production for iOS11/12 using earlier library versions.

**Comment by tianqibt** [comment]
We had similar issue reported a few weeks ago. https://github.com/facebook/facebook-objc-sdk/issues/1013
We have delivered the fix with v5.4.1. Would you please verify that you are using the latest version of SDK and the issue still exist?

**Comment by pomarec** [comment]
With the same versions as @odedharth. I have the issue on simulator but not on device.

**Comment by benpackard** [comment]
I'm using 5.6.0 and experiencing the same issues on simulator (on device is fine).
