### ISSUE TITLE
UIWebView deprecated

### ISSUE THREAD

**Issue by levibostian** [facebook/facebook-objc-sdk#1035]
Today I submitted an app to TestFlight and received this email:

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Foo Beta" 0.5.9 (111). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Best regards,

The App Store Team
```

The app did indeed get submitted to TestFlight successfully where I was able to download the app and use it just fine. However, I would like to avoid having my app rejected in future submissions. 

I went into XCode and searched for `UIView` and did not find my source code use it anywhere except within Bolts and Facebook Share SDK. I am creating issues in both repositories to bring attention of this deprecation that Apple is now enforcing. 

Thanks!

**Comment by levibostian** [comment]
For reference, [Bolts issue I created for the deprecation](https://github.com/BoltsFramework/Bolts-Swift/issues/88)

**Comment by dreamolight** [comment]
Hi @levibostian , please upgrade facebook SDK to latest version (it's v5.5.0 right now). Facebook SDK doesn't depend on Bolts since 5.0 and we removed usage of `UIWebView` in v5.5.0.

**Comment by ranudhurandar** [comment]
how can I remove/update FBSDKLoginKit UIWebView APIs as I am using  FBSDKLoginKit but that has been deprecated. Any help would be appreciated/.
