### ISSUE TITLE
unable to update pod version 5.5.0 

### ISSUE THREAD

**Issue by awthonest** [facebook/facebook-objc-sdk#1037]
please take a look at this issue @dreamolight

Only able to get 5.4.0 version

CocoaPods could not find compatible versions for pod "FacebookSDK/CoreKit":
In Podfile:
FacebookSDK/CoreKit (~> 5.5.0)

None of your spec sources contain a spec satisfying the dependency: FacebookSDK/CoreKit (~> 5.5.0).

Second try with removing core kit
CocoaPods could not find compatible versions for pod "FacebookSDK":
In Podfile:
FacebookSDK(~> 5.5.0)

None of your spec sources contain a spec satisfying the dependency: FacebookSDK(~> 5.5.0).

**Comment by dreamolight** [comment]
Hi @awthonest , could you share your full Podfile file?

**Comment by dreamolight** [comment]
You might need to `pod update` first or `pod install --update-repo`

**Comment by awthonest** [comment]
Thanks @dreamolight it worked
