### ISSUE TITLE
An error occurred while fixing the SDK error.

### ISSUE THREAD

**Issue by JaeKyoungJeon** [facebook/facebook-objc-sdk#1041]
![FBerror](https://user-images.githubusercontent.com/54971178/64616531-b9ea7f00-d417-11e9-92c9-e4a384c53c93.png)

Hi.

An error occurred after building the Facebook SDK with Unity.

please help me.

**Comment by KylinChang** [comment]
Close the issue here, we can discuss in the Unity thread.

**Comment by JaeKyoungJeon** [comment]
@KylinChang  I tried that way and got the first error.
