### ISSUE TITLE
Bolts dependency 

### ISSUE THREAD

**Issue by georgii11** [facebook/facebook-objc-sdk#1042]
Hi,

Is the SDK still depended on _Bolts.Framewrok_?
If yes, are you aware of a version of Bolts which has also replaced _UiWebView_ with _WKWebVIew_? A download link would also be appreciated. 

Thanks,
Georgiana

**Comment by KylinChang** [comment]
Hi @georgii11 , the SDK now doesn't depend on Bolts.Framewrok.
