### ISSUE TITLE
Find window doesn't work with SceneDelegate

### ISSUE THREAD

**Issue by EyalHouzz** [facebook/facebook-objc-sdk#1043]
Hey there!
I have updated to the newest version! thanks!

In our app, we use the iOS SceneDelegate to support multiple windows.
In this [file](https://github.com/facebook/facebook-objc-sdk/blob/323a64bb7364a654630e878b0f032e1d30967f39/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKInternalUtility.m) from the SDK, the function "findWindow" looks up for the keyWindow in UIApplication.shared. But when you use SceneDelegate, you have no keyWindow. It is nil, thus cannot login with FB.

Please advise.

**Comment by dreamolight** [comment]
Hi @EyalHouzz , this is an issue in projects that newly created in Xcode 11, we'll fix it in next release.

**Comment by EyalHouzz** [comment]
Thanks @dreamolight. Do you know when this version will be released? It is a blocker for our iOS 13 version.

**Comment by dreamolight** [comment]
5.6.0 released with support for multi-window apps.

**Comment by EyalHouzz** [comment]
Thanks a lot.

**Comment by HristiyanZahariev** [comment]
This bug still appears for me even when I updated to 5.6.0

**Comment by HristiyanZahariev** [comment]
This bug still appears for me even when I updated to 5.6.0

**Comment by dreamolight** [comment]
Hi @HristiyanZahariev , could you provide a sample project that could reproduce this issue? We've tested at our side and it worked, so we might've not covered all the scenarios.

**Comment by shoaib-akhtar** [comment]
This bug still appears for me even when I updated to 5.7.0

**Comment by ablyBikramjeet** [comment]
Hello Everybody.

I have got new issues today FB login with below IOS 13 if i want to login above IOS 13 then I got this message.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-29 at 18 03 58](https://user-images.githubusercontent.com/52451314/73357117-c0439f80-42c1-11ea-93c7-71c502e7634b.png)

This project had created in Xcode 9.

And I have not used Scene Delegate in this.

Thanks
