### ISSUE TITLE
FBSDKCoreKit has 34 issues that come up when using Xcode Analyze

### ISSUE THREAD

**Issue by ethanwa** [facebook/facebook-objc-sdk#1049]
In Xcode, go to Product > Analyze 

There are a number of the same two issues scattered throughout various files. Here they are:

<img width="294" alt="Screen Shot 2019-09-13 at 10 33 43 PM" src="https://user-images.githubusercontent.com/1653780/64902539-c6b8de00-d676-11e9-8b83-f63305131655.png">

**Comment by dreamolight** [comment]
Hi @ethanwa , thanks for bring this out, I've fixed the nullability issue in https://github.com/facebook/facebook-objc-sdk/commit/995004418220762223619dd8666ccc047a89a16c
