### ISSUE TITLE
renewSystemCredentials method is missing in latest version

### ISSUE THREAD

**Issue by rsekharAppyog** [facebook/facebook-objc-sdk#1050]
We were calling the renewSystemCredentials method every time in didFinishLaunchingWithOptions of our project's Appdelegate file. we have updated to latest version there were so many changes but we are not able to find out the equivalent method for "renewSystemCredentials". 

Is this any alternate method present or no longer needed to call this  method on didFinish.

**Comment by dreamolight** [comment]
Hi @rsekharAppyog , this was deprecated since 4.39.0 and removed in 5.0. System Account login was deprecated by Apple since iOS 12, hence we removed it in SDK. You can safely remove that function call as it doesn't nothing since 4.39.0.
