### ISSUE TITLE
Places Kit and Marketing Kit podspecs are out of date

### ISSUE THREAD

**Issue by SotoiGhost** [facebook/facebook-objc-sdk#1055]
Hi team!

[Places Kit][1] and [Marketing Kit][2] podspecs are out of date.

The most recent version of Places Kit is v5.3.0 and v5.5.0 for Marketing Kit.

Is there a plan to push the podspecs?

Best!

[1]: https://github.com/CocoaPods/Specs/tree/master/Specs/b/5/f/FBSDKPlacesKit
[2]: https://github.com/CocoaPods/Specs/tree/master/Specs/b/c/b/FBSDKMarketingKit

**Comment by tianqibt** [comment]
Hi, currently we do not have any update for Places Kit and Marketing Kit. Once we have any change, we will push new podspecs.
