### ISSUE TITLE
'../AppEvents/Internal/Codeless/FBSDKViewHierarchy.h' file not found

### ISSUE THREAD

**Issue by Liuruyong** [facebook/facebook-objc-sdk#1059]
## Environment

- Xcode Version: `11.0`
- Installation Platform & Verison: `[Cocoapods]` version `1.7.4`

- FBSDKCoreKit (5.0.0):
    - FBSDKCoreKit/Basics (= 5.0.0)
    - FBSDKCoreKit/Core (= 5.0.0)
  - FBSDKCoreKit/Basics (5.0.0)
  - FBSDKCoreKit/Core (5.0.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (5.6.0):
    - FBSDKLoginKit/Login (= 5.6.0)
  - FBSDKLoginKit/Login (5.6.0):
    - FBSDKCoreKit (~> 5.0)
  - FBSDKShareKit (5.6.0):
    - FBSDKShareKit/Share (= 5.6.0)
  - FBSDKShareKit/Share (5.6.0):
    - FBSDKCoreKit (~> 5.0)

## Actual Results

CompileC /Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/Objects-normal/arm64/_FBSDKLoginRecoveryAttempter.o FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/_FBSDKLoginRecoveryAttempter.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/liu/work/cherry_ios/cherry/Pods
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target arm64-apple-ios8.0 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path=/Users/liu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/liu/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_DEBUG=1 -DDEBUG=1 -DCOCOAPODS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fembed-bitcode-marker -index-store-path /Users/liu/Library/Developer/Xcode/DerivedData/Cherry-dknaqtqgqcbjalejgasgglmnmwca/Index/DataStore -iquote /Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/FBSDKLoginKit-generated-files.hmap -I/Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/FBSDKLoginKit-own-target-headers.hmap -I/Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/FBSDKLoginKit-all-non-framework-target-headers.hmap -ivfsoverlay /Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/all-product-headers.yaml -iquote /Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/FBSDKLoginKit-project-headers.hmap -I/Users/liu/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/FBSDKLoginKit/include -I/Users/liu/work/cherry_ios/cherry/Pods/Headers/Private -I/Users/liu/work/cherry_ios/cherry/Pods/Headers/Private/FBSDKLoginKit -I/Users/liu/work/cherry_ios/cherry/Pods/Headers/Public -I/Users/liu/work/cherry_ios/cherry/Pods/Headers/Public/FBSDKCoreKit -I/Users/liu/work/cherry_ios/cherry/Pods/Headers/Public/FBSDKLoginKit -I/Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/DerivedSources-normal/arm64 -I/Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/DerivedSources/arm64 -I/Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/DerivedSources -F/Users/liu/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/FBSDKLoginKit -include /Users/liu/work/cherry_ios/cherry/Pods/Target\ Support\ Files/FBSDKLoginKit/FBSDKLoginKit-prefix.pch -MMD -MT dependencies -MF /Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/Objects-normal/arm64/_FBSDKLoginRecoveryAttempter.d --serialize-diagnostics /Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/Objects-normal/arm64/_FBSDKLoginRecoveryAttempter.dia -c /Users/liu/work/cherry_ios/cherry/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/_FBSDKLoginRecoveryAttempter.m -o /Users/liu/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/FBSDKLoginKit.build/Objects-normal/arm64/_FBSDKLoginRecoveryAttempter.o

In file included from /Users/liu/work/cherry_ios/cherry/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/_FBSDKLoginRecoveryAttempter.m:19:
In file included from /Users/liu/work/cherry_ios/cherry/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/_FBSDKLoginRecoveryAttempter.h:20:
/Users/liu/work/cherry_ios/cherry/Pods/Headers/Private/FBSDKCoreKit/FBSDKCoreKit+Internal.h:24:9: fatal error: '../AppEvents/Internal/Codeless/FBSDKViewHierarchy.h' file not found
#import "../AppEvents/Internal/Codeless/FBSDKViewHierarchy.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by tianqibt** [comment]
Would you please upgrade to FBSDKCoreKit 5.6.0 and verify if the issue still exist?

**Comment by Liuruyong** [comment]
Upgrade to FBSDKCoreKit 5.6.0, it works.

**Comment by Liuruyong** [comment]
Please update pods dependencies.

`- FBSDKLoginKit (5.6.0):
    - FBSDKLoginKit/Login (= 5.6.0)
  - FBSDKLoginKit/Login (5.6.0):
    - FBSDKCoreKit (~> 5.0)`

**Comment by alconasoftware** [comment]
I am having this same problem with a flutter install. Can you tell me how to make this fix in flutter?

**Comment by kushalpal17** [comment]
I am also getting this issue. I am using pod 'FBSDKLoginKit', '5.6.0'

**Comment by maxmitchenko** [comment]
> I am having this same problem with a flutter install. Can you tell me how to make this fix in flutter?

I'm trying to fix this problem for two days...

**Comment by maxmitchenko** [comment]
<img width="937" alt="Screenshot 2020-03-31 at 11 08 50" src="https://user-images.githubusercontent.com/47216894/78002725-4de25080-7340-11ea-8e8a-6f37c1ef979f.png">
